### ISSUE TITLE
Issus when running more than a replica for HA

### ISSUE THREAD

**Issue by JesusRo** [kinvolk/nebraska#388]
## Description

Errors running randomly when deployment has more than 1 replica

## Impact

Operations are not performed (example: create group)

## Environment and steps to reproduce

1. **Set-up**: 
Deployed via helm chart with replicaCount: 2

## Expected behavior

Operation are correctly applied

## Additional information

```bash
runtime error: invalid memory address or nil pointer dereference
runtime/panic.go:199 (0x4451eb)
runtime/signal_unix.go:394 (0x445028)
github.com/kinvolk/nebraska@/cmd/nebraska/controller.go:339 (0xda8809)
github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x999fba)
github.com/kinvolk/nebraska@/cmd/nebraska/controller.go:167 (0xda66ee)
github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x999fba)
github.com/Depado/ginprom@v1.7.0/prom.go:323 (0xda4f7a)
github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x999fba)
github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0x9ac873)
github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x999fba)
github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x9a3efc)
github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x9a35fd)
net/http/server.go:2831 (0x72dc53)
net/http/server.go:1919 (0x7294f4)
runtime/asm_amd64.s:1357 (0x45d360)


<nil> ERR addGroup - adding group &{e4657731-2362-404e-a45c-ad14e9ee990c flatcar-k8s.test flatcar-k8s.test 0001-01-01 00:00:00 +0000 UTC false e96281a6-d1af-4bde-9a0a-97b76e56dc57 {{e06064ad-4414-4904-9a6e-fd465593d1b2 true}} true false false {{Europe/Madrid true}} 1 hours 999999 60 days <nil> flatcar-k8s.test} error="ERROR: duplicate key value violates unique constraint \"groups_application_id_name_key\" (SQLSTATE 23505)" context=nebraska
```

**Comment by joaquimrocha** [comment]
@mkilchhofer , maybe you have insights on what we need to make multiple replicas behave better.
It seems it's trying to insert the group multiple times.

**Comment by mkilchhofer** [comment]
I think the software developers need to make sure everything from the software-side supports multiple replicas (leader election, app clustering, etc.).

The only thing we can do on the Kubernetes side to mitigate the most critical pain points is to use sticky sessions on the Ingress, but config depends on what Ingress controller the endusers are using. For [ingress-nginx](https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/):
```yaml
ingress:
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "INGRESSCOOKIE"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
```
