### ISSUE TITLE
[RFE] Add revisionHistoryLimit to deployment on helm chart

### ISSUE THREAD

**Issue by JesusRo** [kinvolk/nebraska#494]
## Current situation
Namespace is flooded with replicasets after several deployments

## Impact
Not real impact, just forcing people to do manual housekeeping

## Ideal future situation
Set a default revisionHistoryLimit for the deployment to 3? 5?
Allow modification via values

## **Implementation options
Add revisionHistoryLimit
[deployment.yaml](https://github.com/kinvolk/nebraska/blob/main/charts/nebraska/templates/deployment.yaml#L11)
```yaml
  [...]
  spec:
    replicas: {{ .Values.replicaCount }}
+   revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
    strategy:
  [...]
```
and it's default values
[values.yaml](https://github.com/kinvolk/nebraska/blob/main/charts/nebraska/values.yaml#L6)
```yaml
  [...]
  replicaCount: 1
+ revisionHistoryLimit: 3

  image:
  [...]
```
